version: '3.8'
services:
  web89:
    image: php:8.2-apache
    container_name: Tp-Docker-pt1
    volumes:
      - ./Docker-pt1/html:/usr/local/apache2
    ports:
      - 89:80


  mysql:
    image: mysql:5.7
    container_name: mysql123
    environment:
      MYSQL_DATABASE: tp2
      MYSQL_USER: zinedine
      MYSQL_PASSWORD: Bonjour!
      MYSQL_ROOT_PASSWORD: aled
      UPLOAD_LIMIT: 20M
    ports:
    - 3306:3306
    volumes:
    - ./Docker-pt1/mysql:/usr/local/mysql


