version: '3.8'
services:
  web89:
    image: php:8.2-apache
    container_name: Tp-Docker-pt1
    volumes:
      - ./html:/var/www/html
    ports:
      - 82:80
  mysql:
    image: mysql:5.7
    container_name: mysql123
    environment:
      MYSQL_DATABASE: tp2
      MYSQL_USER: zinedine
      MYSQL_PASSWORD: Bonjour!
      MYSQL_ROOT_PASSWORD: aled
      UPLOAD_LIMIT: 20M
    ports:
      - 3306:3306
    volumes:
      - ./Docker-pt1/mysql:/usr/local/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    ports:
      - 83:80
    environment:
      - PMA_HOST=mysql



